// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Stemming.Models;
using System;

namespace Stemming.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180606165610_root suffic input and stopwords")]
    partial class rootsufficinputandstopwords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Stemming.Models.InputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InputName");

                    b.Property<int?>("RootModelId");

                    b.Property<int?>("SuffixModelId");

                    b.HasKey("Id");

                    b.HasIndex("RootModelId");

                    b.HasIndex("SuffixModelId");

                    b.ToTable("tblInput");
                });

            modelBuilder.Entity("Stemming.Models.RootModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RootName");

                    b.HasKey("Id");

                    b.ToTable("tblRoot");
                });

            modelBuilder.Entity("Stemming.Models.StopWordModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StopWord");

                    b.HasKey("Id");

                    b.ToTable("tblStopword");
                });

            modelBuilder.Entity("Stemming.Models.SuffixModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SuffixName");

                    b.HasKey("Id");

                    b.ToTable("tblSuffix");
                });

            modelBuilder.Entity("Stemming.Models.InputModel", b =>
                {
                    b.HasOne("Stemming.Models.RootModel")
                        .WithMany("Inputs")
                        .HasForeignKey("RootModelId");

                    b.HasOne("Stemming.Models.SuffixModel")
                        .WithMany("Inputs")
                        .HasForeignKey("SuffixModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
